### ISSUE TITLE
Rename directories

### ISSUE THREAD

**Issue by khalidchawtany** [gabrielpoca/replacer.nvim#1]
I cannot rename directories. Is there any way to accomplish that?

**Comment by gabrielpoca** [comment]
Hey @khalidchawtany I'm not sure, I need more info about your use-case. For me, renaming a directory is the same as moving all files inside one directory to another directory.

**Comment by khalidchawtany** [comment]
I want to turn this:
```
$ tree
.
├── 1
│   └── f2
└── f1
```
into this:
```
$ tree
.
├── 2
│   └── f3
└── f1
```

Notice how the dir name and the file inside it are both renamed

**Comment by gabrielpoca** [comment]
@khalidchawtany that's possible. You just need a quick fix window with the `1/f2` and then open up replacer.vim, then change the `1` to `2` and `f2` to `f3`. I just tested and it works 👍

**Comment by khalidchawtany** [comment]
Yes, but the directory named `1` does not get renamed. Instead another directory is created with the new name and the old directory remains!

**Comment by gabrielpoca** [comment]
You're right. The files are moved to another directory, and the old one stays where it is. We could check if the directory is empty and remove it. But as it is, there's no way around it.

**Comment by gabrielpoca** [comment]
Fixed in https://github.com/gabrielpoca/replacer.nvim/commit/981b1c3830e8b0dd7fc1ad125609f5caffff5bfa
