### ISSUE TITLE
E5108

### ISSUE THREAD

**Issue by lvim-tech** [gabrielpoca/replacer.nvim#15]
E5108: Error executing lua: BufWinEnter Autocommands for "*"..function <SNR>49_Highlight_Matching_Pair, line 149: Vim(call):E801: ID already taken: 3
stack traceback:
	[C]: in function 'bufload'
	...ocal/share/nvim/lazy/replacer.nvim/lua/replacer/init.lua:183: in function 'run'

**Comment by gabrielpoca** [comment]
Hey 👋 thank you for opening the issue. Can you tell me the steps to reproduce?

**Comment by lvim-tech** [comment]
just run replacer - lua require("replacer").run()
