### ISSUE TITLE
Delete Lines

### ISSUE THREAD

**Issue by dhulihan** [gabrielpoca/replacer.nvim#17]
This plugin is great! Thanks so much for creating it! ❤️ 

Apologies if this is already possible, but I'd love to be able to delete matches/lines from the editable quickfix window, and have those lines be deleted in their respective files.

**Comment by dhulihan** [comment]
Short term, I can replace the line with whitespace, and that works well in a pinch (though I have to clean up the whitespace with a formatted afterwards).

**Comment by gabrielpoca** [comment]
Hey @dhulihan thank you for reaching out. Your solution is the one I use, but I've looked into this a bit, and I think this comment in a similar plugin makes sense https://github.com/stefandtw/quickfix-reflector.vim/issues/20#issuecomment-294520851 the idea is that you can easily do this with a macro and the quickfix window, you don't really need replacer.nvim to delete the lines.

**Comment by dhulihan** [comment]
No worries, thanks for the suggestion and reply @gabrielpoca !
