### ISSUE TITLE
Colon deleted on write

### ISSUE THREAD

**Issue by JA-Bar** [gabrielpoca/replacer.nvim#3]
Hello, great plugin!

I was checking it out and noticed that during search and replace it mistakenly deleted a colon. Consider the following file:
 ```python3
# some_file.py
def some_function():
    print('hello, world!')


if __name__ == '__main__':
    some_function()
```

If you populate the quickfix list by searching for `some_function`, and activate the plugin, the result is the following:
```
./data_and_algos/recursion/something.py:    some_function()
./data_and_algos/recursion/something.py:def some_function():
```
After doing a search and replace of the function name (i.e. `:%s/some_function/another_function/g`) and using `:w` to save the buffer, the content of the file changes to:

```python3
# some_file.py
def another_function()
    print('hello, world!')


if __name__ == '__main__':
    another_function()
```

Renaming the function as expected, but deleting the colon in the function definition, causing a syntax error.
I glanced over the code and it may be related to how the parsing of the quickfix list buffer uses `:` as a separating character, not sure though.

**Comment by gabrielpoca** [comment]
@JA-Bar thank you for taking the time to report it! I believe this fixes it https://github.com/gabrielpoca/replacer.nvim/commit/85e046b68c14add0a760a39f5104dde3bab6149b would you mind trying again? It seems that `vim.fn.split` removes the first or last elements when it's empty.

**Comment by JA-Bar** [comment]
That does it. Thanks for the quick response!
