### ISSUE TITLE
Slow for edits of only content of file

### ISSUE THREAD

**Issue by AckslD** [gabrielpoca/replacer.nvim#4]
When changing for example only the content of a single file through replacer it is very slow. I can understand that this happens if it needs to rename many files but maybe there could be a check to see if the files have actually changed and if not then only work on the buffers.

With such a check it might be possible to also allow to undo after?

**Comment by gabrielpoca** [comment]
I think the issue is that the code is calling `vim.fn.writefile` for every line that's changed. If you changed 1000 lines in a file, it calls it 1000 times. The undo part is also interesting, I never undo on the file itself, I usually just undo on the quickfix window. I'll have a look 👍

**Comment by AckslD** [comment]
@gabrielpoca cool!

Btw, how do you mean undo with the quickfix window?

**Comment by gabrielpoca** [comment]
I changed the code so every file is only written once, but it didn't solve the issue for huge files. I did some reading and if I disable fsync on the writefile function, and that solves it. My understanding is that we use fsync to ensure an operation is full written to the hard disk in case of a system failure, so I guess it's safe to disable? Worst case scenario you can always run the change again? What do you think? I opened a pull request https://github.com/gabrielpoca/replacer.nvim/pull/5 while I'm trying out the changes for a couple of days.

If I need to undo after a replace, I'll just "undo" on the replacer.nvim window and save it again :p

**Comment by AckslD** [comment]
Sounds great @gabrielpoca! I will try to give it a shot but am a bit busy atm :)

How does that work actually cause if I've made a substitution `s/a/b` and I undo the replacer window which then maybe has a substitution `s/a/c`, then if I apply that to some files it won't "undo" what `s/a/b` did? But maybe I'm misunderstanding something :)

**Comment by gabrielpoca** [comment]
I've been using the changes for a couple of weeks now and it seems to be working fine.


@AckslD I was misunderstanding your question, yeah, that won't work
