### ISSUE TITLE
Feature: delete lines in quickfix

### ISSUE THREAD

**Issue by dsummersl** [gabrielpoca/replacer.nvim#6]
Coming from https://github.com/stefandtw/quickfix-reflector.vim I rely heavily on the ability to delete lines in the quickfix window: put some search results into the quickfix window, delete any entries not applicable to whatever change I need to make in the quickfix window, then use :%s on whats left.

Would love to see a feature like that in this plugin

**Comment by gabrielpoca** [comment]
Hey @dsummersl, I've had a couple of opportunities to think about this, and I still can't find a simple solution. I think that for me, you filter out what you don't need before you run this plugin. You can still delete lines from the quickfix window before your run replace.nvim . I'm sorry for not having a better answer.

**Comment by Shatur** [comment]
That's bad. Why it's impossible to do the same as in https://github.com/stefandtw/quickfix-reflector.vim? You can't always filter the quickfix in a convenient way. VSCode, for example, allows users to delete extra matches manually.

**Comment by gabrielpoca** [comment]
you can always delete the lines before running the plugin. Unfortunately, I can't take the same approach as quickfix-reflector because I have to transform the quickfix into something else in order to add the file paths

**Comment by Shatur** [comment]
Oh, I get it, you are right.

**Comment by dsummersl** [comment]
Thanks for checking it out @gabrielpoca - much appreciated. I'll stick with quickfix-reflector.vim for the time being as I have the full power of buffer editing (:s, :g, dd, etc) -- sadly without the ability to move/rename :'(
