### ISSUE TITLE
Expected Lua number on 0.7.0 nightly

### ISSUE THREAD

**Issue by gegoune** [gabrielpoca/replacer.nvim#9]
Running `:lua require('replacer').run()` on 
```
NVIM v0.7.0-dev+870-g43b95b543
Build type: Release
LuaJIT 2.1.0-beta3
```
produces this error:

```lua
E5108: Error executing lua ...te/pack/packer/start/replacer.nvim/lua/replacer/init.lua:60: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...te/pack/packer/start/replacer.nvim/lua/replacer/init.lua:60: in function 'run'
        [string ":lua"]:1: in main chunk
```

There was a breaking change recently in Neovim which most likely caused it, it was something about bufnr parameter to `nvim_buf_set_option` no longer treating `nil` as current buffer, or something of that sort, can't remember exactly. And it seems like at the time of execution of line 60 `qf_bufnr` is not known yet/`nil`?

**Comment by gabrielpoca** [comment]
@gegoune thank you for reporting. It's actually a bug I introduced recently in https://github.com/gabrielpoca/replacer.nvim/commit/7fa79894c77d3236b1cef488acde220593113c0b#diff-4404157303c9cd32687b127cb50486b8ca5c6d2cdf1933cb6c50fdd2e77f2159R60 It's a copy-paste from the previous line that somehow doesn't break.

**Comment by gegoune** [comment]
Because previous line's function call has `buffer` as first argument rather than `qf_bufnr` which doesn't exist in that execution context. I think just changing it to `bufnr` should fix it. Would you want me to send a PR?

**Comment by gabrielpoca** [comment]
@gegoune the line is not needed, it's only supposed to exist in the other file. Can you try with the latest change?

**Comment by gegoune** [comment]
@gabrielpoca, working now, thanks! (great plugin!)
